name: ZeusCraft
version: 1.0
author: Henry
main: me.prime.ZeusServer.Main
description: Adds bank and stuff

commands:
  smite:
    description: /smite <Player> Smites a player by striking them with lighting.