name: ZeusCraft
version: 1.0
author: Henry
main: me.prime.ZeusServer.Main
description: Adds bank and stuff

commands:
  smite:
    description: ChatColor.GOLD + /smite <Player> ChatColor.GREEN + Smites a player by striking them with lighting.